App\Entity\Account:
    operations:
        ApiPlatform\Metadata\Get: ~
        ApiPlatform\Metadata\GetCollection: ~
        ApiPlatform\Metadata\Post: ~
        ApiPlatform\Metadata\Put: ~
        ApiPlatform\Metadata\Patch: ~
        ApiPlatform\Metadata\Delete: ~
