api_platform:
    swagger:
        http_auth:
            JWT:
                scheme: bearer
                bearerFormat: JWT
    formats:
        json:
            mime_types:
                - 'application/json'
        jsonld:
            mime_types:
                - 'application/ld+json'
