<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260820131347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ledger_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exchange_rate NUMERIC(15, 6) NOT NULL, source_amount NUMERIC(15, 2) NOT NULL, target_amount NUMERIC(15, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, transfer_id INT NOT NULL, from_currency_id INT NOT NULL, to_currency_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E3FD73F4537048AF ON ledger_entries (transfer_id)');
        $this->addSql('CREATE INDEX IDX_E3FD73F4A66BB013 ON ledger_entries (from_currency_id)');
        $this->addSql('CREATE INDEX IDX_E3FD73F416B7BF15 ON ledger_entries (to_currency_id)');
        $this->addSql('ALTER TABLE ledger_entries ADD CONSTRAINT FK_E3FD73F4537048AF FOREIGN KEY (transfer_id) REFERENCES transfer (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ledger_entries ADD CONSTRAINT FK_E3FD73F4A66BB013 FOREIGN KEY (from_currency_id) REFERENCES currency (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ledger_entries ADD CONSTRAINT FK_E3FD73F416B7BF15 FOREIGN KEY (to_currency_id) REFERENCES currency (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ledger_entries DROP CONSTRAINT FK_E3FD73F4537048AF');
        $this->addSql('ALTER TABLE ledger_entries DROP CONSTRAINT FK_E3FD73F4A66BB013');
        $this->addSql('ALTER TABLE ledger_entries DROP CONSTRAINT FK_E3FD73F416B7BF15');
        $this->addSql('DROP TABLE ledger_entries');
    }
}
