<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260819082441 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE transfer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, amount NUMERIC(15, 2) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sender_account_id INT DEFAULT NULL, receiver_account_id INT DEFAULT NULL, currency_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4034A3C05F37A13B ON transfer (token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4034A3C0AEA34913 ON transfer (reference)');
        $this->addSql('CREATE INDEX IDX_4034A3C0CFEF0177 ON transfer (sender_account_id)');
        $this->addSql('CREATE INDEX IDX_4034A3C0D8CF5973 ON transfer (receiver_account_id)');
        $this->addSql('CREATE INDEX IDX_4034A3C038248176 ON transfer (currency_id)');
        $this->addSql('ALTER TABLE transfer ADD CONSTRAINT FK_4034A3C0CFEF0177 FOREIGN KEY (sender_account_id) REFERENCES account (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transfer ADD CONSTRAINT FK_4034A3C0D8CF5973 FOREIGN KEY (receiver_account_id) REFERENCES account (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transfer ADD CONSTRAINT FK_4034A3C038248176 FOREIGN KEY (currency_id) REFERENCES currency (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE transfer DROP CONSTRAINT FK_4034A3C0CFEF0177');
        $this->addSql('ALTER TABLE transfer DROP CONSTRAINT FK_4034A3C0D8CF5973');
        $this->addSql('ALTER TABLE transfer DROP CONSTRAINT FK_4034A3C038248176');
        $this->addSql('DROP TABLE transfer');
    }
}
