<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260818081236 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE currency (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(255) NOT NULL,
              name VARCHAR(255) NOT NULL,
              symbol VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6956883F77153098 ON currency (code)');
        $this->addSql('ALTER TABLE account ADD currency_id INT NOT NULL');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              account
            ADD
              CONSTRAINT FK_7D3656A438248176 FOREIGN KEY (currency_id) REFERENCES currency (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql('CREATE INDEX IDX_7D3656A438248176 ON account (currency_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account DROP CONSTRAINT FK_7D3656A438248176');
        $this->addSql('DROP INDEX IDX_7D3656A438248176');
        $this->addSql('ALTER TABLE account DROP currency_id');
        $this->addSql('DROP TABLE currency');
    }
}
