<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260819131533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exchange_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rate NUMERIC(10, 4) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, base_currency_id INT NOT NULL, target_currency_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E9521FAB3101778E ON exchange_rate (base_currency_id)');
        $this->addSql('CREATE INDEX IDX_E9521FABBF1ECE7C ON exchange_rate (target_currency_id)');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT FK_E9521FAB3101778E FOREIGN KEY (base_currency_id) REFERENCES currency (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT FK_E9521FABBF1ECE7C FOREIGN KEY (target_currency_id) REFERENCES currency (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exchange_rate DROP CONSTRAINT FK_E9521FAB3101778E');
        $this->addSql('ALTER TABLE exchange_rate DROP CONSTRAINT FK_E9521FABBF1ECE7C');
        $this->addSql('DROP TABLE exchange_rate');
    }
}
