<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260821100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create fees table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE fees (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) DEFAULT 'free charged' NOT NULL, amount NUMERIC(10, 2) DEFAULT '0.00' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, transfer_id INT NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE INDEX IDX_4CE1C7A4537048AF ON fees (transfer_id)');
        $this->addSql('ALTER TABLE fees ADD CONSTRAINT FK_4CE1C7A4537048AF FOREIGN KEY (transfer_id) REFERENCES transfer (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE fees DROP CONSTRAINT FK_4CE1C7A4537048AF');
        $this->addSql('DROP INDEX IDX_4CE1C7A4537048AF');
        $this->addSql('DROP TABLE fees');
    }
}
